---
# matrix.org config
# base-url: 'https://matrix.org'
# announcements-room: '!OfRBJBuhWHWNKplCtn:matrix.org'
# message-board-room: '!kgfNoSRLkBFxmVGvxw:matrix.org'
# client-user-id: '@pedro_test:matrix.org'
# client-access-token: 'MDAxOGxvY2F0aW9uIG1hdHJpeC5vcmcKMDAxM2lkZW50aWZpZXIga2V5CjAwMTBjaWQgZ2VuID0gMQowMDI5Y2lkIHVzZXJfaWQgPSBAcGVkcm9fdGVzdDptYXRyaXgub3JnCjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5vbmNlID0gKzMjLFI5blJNUTgyVS1LZAowMDJmc2lnbmF0dXJlINMcSs_OD2POtXIpgk_LzZJalIhvToEuwOr-8r6hApQ3Cg'

# communi.camp config
base-url: 'https://communi.camp'
announcements-room: '!cLycyFOevWWqdGhQqk:communi.camp'
message-board-room: '!hRaDEvHwSNCiLSbjzs:communi.camp'
client-user-id: '@news:communi.camp'
client-access-token: 'MDAxYWxvY2F0aW9uIGNvbW11bmkuY2FtcAowMDEzaWRlbnRpZmllciBrZXkKMDAxMGNpZCBnZW4gPSAxCjAwMjVjaWQgdXNlcl9pZCA9IEBuZXdzOmNvbW11bmkuY2FtcAowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25jZSA9IEpmTFJRX3gqNGFDWGRYXjAKMDAyZnNpZ25hdHVyZSBCqqE2BVHDcxKT0vP54dcpCOp8xeGSA0MvH6YYdCzZDwo'
